# Generated by Django 5.2.6 on 2025-10-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trip_covers/'),
        ),
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_joinable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='location_summary',
            field=models.CharField(blank=True, help_text='e.g., Goa, India', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_picture',
            field=models.ImageField(default='background_pics/default_bg.jpg', upload_to='background_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.post')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='DayPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='day_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.tripday')),
            ],
        ),
    ]
