# Generated by Django 5.2.6 on 2026-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_group_alter_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
