# Generated by Django 5.2.6 on 2025-10-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_follow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
    ]
