# Generated by Django 5.2.6 on 2026-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_story_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencepost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencepost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinabletrippost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinabletrippost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
